<a href="https://colab.research.google.com/github/BagaskaraAdhi/UTSTextMining/blob/main/2318090BagaskaraAdhiPradana3OperasiTextVectorizer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. Mount Google Drive & Load Dataset**

In [ ]:
from google.colab import drive
import pandas as pd
import numpy as np

# Menyambungkan ke Google Drive
drive.mount('/content/drive')

# Mengambil dataset dari path UTS kamu
path = '/content/drive/MyDrive/Text Mining/UTS/Dataset/GojekAppReviewV4.0.0-V4.9.3_Cleaned.csv'
df = pd.read_csv(path)

# MENAMPILKAN 10 DATA PERTAMA DARI DATASET ASLI
print("--- 10 Baris Pertama Dataset Asli ---")
display(df.head(10))

# Preprocessing: Menghapus data kosong dan sampling 1000 data
df = df.dropna(subset=['content'])
documents = df['content'].head(1000).astype(str).tolist()

print(f"\nBerhasil memuat {len(documents)} dokumen untuk diproses.")
print("=" * 60)

output_path = '/content/drive/MyDrive/Text Mining/UTS/Dataset/'

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
--- 10 Baris Pertama Dataset Asli ---


,userName,content,score,at,appVersion
0,Yuga Edit,akun gopay saya di blok,1,2022-01-21 10:52:12,4.9.3
1,ff burik,Lambat sekali sekarang ini bosssku apk gojek g...,3,2021-11-30 15:40:38,4.9.3
2,Anisa Suci Rahmayuliani,Kenapa sih dari kemarin sy buka aplikasi gojek...,4,2021-11-29 22:58:12,4.9.3
3,naoki yakuza,Baru download gojek dan hape baru trus ditop u...,1,2022-09-03 15:21:17,4.9.3
4,Trio Sugianto,Mantap,5,2022-01-15 10:05:27,4.9.3
5,Arlan Ramlan,Bagus,4,2022-02-01 05:50:40,4.9.3
6,Slamet Hariyanto,Coba dulu,2,2021-12-10 22:40:45,4.9.3
7,Hasan Thio,Ok,5,2022-02-01 03:07:45,4.9.3
8,RAFI BADZLIN,Gimana ini kak pin saya salah terus padahal ud...,1,2022-12-17 08:56:52,4.9.3
9,mariyadi qc,Biar aman kamu tidak bisa pakai gojek Jadi say...,1,2022-02-09 11:27:38,4.9.3



Berhasil memuat 1000 dokumen untuk diproses.


# **2. Bag Of Words (BOW)**

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer_bow = CountVectorizer()
vectors_bow = vectorizer_bow.fit_transform(documents)
feature_names_bow = vectorizer_bow.get_feature_names_out()

# Tampilkan 10 data/kolom pertama di Colab
print("--- Hasil Bag Of Words (10 Kolom Pertama) ---")
print("Fitur:", feature_names_bow[:10])
print(vectors_bow.toarray()[:10, :10]) # 10 baris x 10 kolom

# Simpan ke Excel
df_bow = pd.DataFrame(vectors_bow.toarray(), columns=feature_names_bow)
df_bow.to_excel('Hasil_BoW_Gojek.xlsx', index=False)
print("\n> File 'Hasil_BoW_Gojek.xlsx' berhasil dibuat.")
df_bow.to_excel(output_path + 'Hasil_BoW_Gojek.xlsx', index=False)
print(f"\n> File 'Hasil_BoW_Gojek.xlsx' tersimpan di: {output_path}")

--- Hasil Bag Of Words (10 Kolom Pertama) ---
Fitur: ['0100' '0130' '04' '09km' '10' '100' '100000' '100k' '100kg' '11000']
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]

> File 'Hasil_BoW_Gojek.xlsx' berhasil dibuat.

> File 'Hasil_BoW_Gojek.xlsx' tersimpan di: /content/drive/MyDrive/Text Mining/UTS/Dataset/


# **3. TF-ID**

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer_tfidf = TfidfVectorizer()
vectors_tfidf = vectorizer_tfidf.fit_transform(documents)
feature_names_tfidf = vectorizer_tfidf.get_feature_names_out()

# Tampilkan 10 data/kolom pertama di Colab
print("--- Hasil TF-IDF (10 Kolom Pertama) ---")
print("Fitur:", feature_names_tfidf[:10])
print(vectors_tfidf.toarray()[:10, :10]) # 10 baris x 10 kolom

# Simpan ke Excel
df_tfidf = pd.DataFrame(vectors_tfidf.toarray(), columns=feature_names_tfidf)
df_tfidf.to_excel('Hasil_TFIDF_Gojek.xlsx', index=False)
print("\n> File 'Hasil_TFIDF_Gojek.xlsx' berhasil dibuat.")
df_tfidf.to_excel(output_path + 'Hasil_TFIDF_Gojek.xlsx', index=False)
print(f"> File 'Hasil_TFIDF_Gojek.xlsx' tersimpan di: {output_path}")

--- Hasil TF-IDF (10 Kolom Pertama) ---
Fitur: ['0100' '0130' '04' '09km' '10' '100' '100000' '100k' '100kg' '11000']
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

> File 'Hasil_TFIDF_Gojek.xlsx' berhasil dibuat.
> File 'Hasil_TFIDF_Gojek.xlsx' tersimpan di: /content/drive/MyDrive/Text Mining/UTS/Dataset/


# **4. Word Embedding (Word2Vec)**

In [ ]:
from gensim.models import Word2Vec

# Tokenisasi (Word2Vec butuh list kata)
sentences = [text.lower().split() for text in documents]

# Training model Word2Vec (100 dimensi sesuai modul)
model_w2v = Word2Vec(sentences, vector_size=100, window=5, min_count=1, workers=4)

# Tampilkan 10 dimensi pertama dari kata 'gojek'
print("--- Hasil Word Embedding (10 Dimensi Pertama kata 'gojek') ---")
if 'gojek' in model_w2v.wv:
    print(model_w2v.wv['gojek'][:10])

# Simpan hasil Word Vectors ke Excel (Kata -> Vektor 100 Dimensi)
words = list(model_w2v.wv.index_to_key)
word_vectors = [model_w2v.wv[word] for word in words]
df_w2v = pd.DataFrame(word_vectors, index=words)
df_w2v.to_excel('Hasil_Word2Vec_Gojek.xlsx')
print("\n> File 'Hasil_Word2Vec_Gojek.xlsx' berhasil dibuat.")
df_w2v.to_excel(output_path + 'Hasil_Word2Vec_Gojek.xlsx')
print(f"> File 'Hasil_Word2Vec_Gojek.xlsx' tersimpan di: {output_path}")

--- Hasil Word Embedding (10 Dimensi Pertama kata 'gojek') ---
[-0.01425378  0.03464757  0.00598081  0.00453477  0.01777232 -0.04388612
  0.02040668  0.06950913 -0.01364554 -0.02056512]

> File 'Hasil_Word2Vec_Gojek.xlsx' berhasil dibuat.
> File 'Hasil_Word2Vec_Gojek.xlsx' tersimpan di: /content/drive/MyDrive/Text Mining/UTS/Dataset/
